### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by nealsanche**
There seems to be a push toward getting projects set up to use as few legacy dependencies as possible. While Shared Preferences Mock isn't something that an app would be distributing in release builds, it still shows up on the list of projects that tools like [Can I Drop Jetifier](https://github.com/plnice/can-i-drop-jetifier) enumerates as not using AndroidX libraries.

This PR brings the project up to AndroidX dependencies.

### CODE REVIEW

**Comment by nealsanche** [comment]
I have no idea what would make Travis happy at this point.

**Comment by nealsanche** [comment]
Okay, looks like I made Travis happy. Now, hopefully we can make the original author happy.

**Review by IvanShafran — APPROVED** [review]
Good job!

**Comment by IvanShafran** [comment]
@nealsanche Hi! Thank you for your contribution! I missed the notification for this PR somehow. Shame on me. Anyway, I am going to merge this and publish 1.1 Jitpack version.

**Pull request merged**
